/**
 * Contract Artifacts — Local Re-export
 *
 * Re-exports compiled contract artifacts from the contracts package
 * to stay within apps/api/src rootDir for TypeScript compilation.
 *
 * The actual artifacts are generated by scripts/compile-contracts.ts.
 */

// @ts-ignore — cross-package import, resolved at runtime by tsx/node
export { ContractArtifacts, type ContractName } from "../../../../../contracts/compiled/artifacts.js";
