/**
 * Compiles all Solidity contracts in contracts/src/ and outputs
 * ABI + bytecode to contracts/compiled/artifacts.ts
 *
 * Usage: npx tsx scripts/compile-contracts.ts
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import solc from "solc";

const __dirname = dirname(fileURLToPath(import.meta.url));

const CONTRACTS_DIR = resolve(__dirname, "..", "contracts", "src");
const OUT_DIR = resolve(__dirname, "..", "contracts", "compiled");

function collectSources(dir: string, prefix = ""): Record<string, { content: string }> {
  const sources: Record<string, { content: string }> = {};
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = resolve(dir, entry.name);
    const key = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      Object.assign(sources, collectSources(fullPath, key));
    } else if (entry.name.endsWith(".sol")) {
      sources[key] = { content: readFileSync(fullPath, "utf-8") };
    }
  }
  return sources;
}

const sources = collectSources(CONTRACTS_DIR);
console.log(`Found ${Object.keys(sources).length} Solidity files:`);
for (const name of Object.keys(sources)) {
  console.log(`  - ${name}`);
}

const input = {
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: {
      "*": {
        "*": ["abi", "evm.bytecode.object"],
      },
    },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

if (output.errors) {
  const fatal = output.errors.filter((e: any) => e.severity === "error");
  if (fatal.length > 0) {
    console.error("Compilation errors:");
    for (const err of fatal) {
      console.error(err.formattedMessage);
    }
    process.exit(1);
  }
  for (const warn of output.errors.filter((e: any) => e.severity === "warning")) {
    console.warn(`⚠ ${warn.formattedMessage.split("\n")[0]}`);
  }
}

const TARGET_CONTRACTS = [
  "AquaAgentPolicyGuard",
  "MitigationExecutor",
  "BufferVault",
  "AquaAgent",
  "CCIPCoordinator",
];

const artifacts: Record<string, { abi: any[]; bytecode: string }> = {};

for (const [fileName, fileContracts] of Object.entries(output.contracts || {})) {
  for (const [contractName, contractData] of Object.entries(fileContracts as Record<string, any>)) {
    if (TARGET_CONTRACTS.includes(contractName)) {
      artifacts[contractName] = {
        abi: contractData.abi,
        bytecode: `0x${contractData.evm.bytecode.object}`,
      };
      console.log(`✓ Compiled ${contractName} (${contractData.evm.bytecode.object.length / 2} bytes)`);
    }
  }
}

const missing = TARGET_CONTRACTS.filter((name) => !artifacts[name]);
if (missing.length > 0) {
  console.error(`Missing contracts: ${missing.join(", ")}`);
  process.exit(1);
}

if (!existsSync(OUT_DIR)) {
  mkdirSync(OUT_DIR, { recursive: true });
}

const tsContent = `// Auto-generated by scripts/compile-contracts.ts — do not edit manually
// Compiled from contracts/src/*.sol using solc ${solc.version()}

export const ContractArtifacts = ${JSON.stringify(artifacts, null, 2)} as const;

export type ContractName = keyof typeof ContractArtifacts;
`;

writeFileSync(resolve(OUT_DIR, "artifacts.ts"), tsContent, "utf-8");
console.log(`\nArtifacts written to contracts/compiled/artifacts.ts`);
